# Generated by Django 4.0.4 on 2022-05-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_site_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=128, verbose_name="nombres"),
        ),
        migrations.AlterField(
            model_name="user",
            name="identification_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "C.C."),
                    (2, "C.E."),
                    (3, "Pasaporte"),
                    (4, "NUIP"),
                ],
                null=True,
                verbose_name="tipo de documento",
            ),
        ),
    ]
